create or replace function public.is_current_user_hr_admin()
returns boolean
language sql
security definer
stable
set search_path = public, auth
as $$
  select coalesce(
    (
      select
        coalesce((u.raw_user_meta_data ->> 'is_admin')::boolean, false)
        or coalesce(u.raw_user_meta_data ->> 'role' = 'admin', false)
        or coalesce(u.raw_app_meta_data ->> 'role' = 'admin', false)
      from auth.users u
      where u.id = auth.uid()
    ),
    false
  );
$$;

create or replace function public.assert_hr_admin()
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.is_current_user_hr_admin() then
    raise exception 'Acceso denegado. Solo administradores de RRHH pueden ejecutar esta accion.';
  end if;
end;
$$;

create or replace function public.get_employee_directory()
returns table (
  user_id uuid,
  email text,
  display_name text,
  nombre text,
  apellidos text,
  is_admin boolean,
  is_active boolean,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  perform public.assert_hr_admin();

  return query
  select
    u.id as user_id,
    u.email::text as email,
    coalesce(
      nullif(u.raw_user_meta_data ->> 'display_name', ''),
      nullif(u.raw_user_meta_data ->> 'full_name', ''),
      nullif(trim(concat_ws(' ', u.raw_user_meta_data ->> 'nombre', u.raw_user_meta_data ->> 'apellidos')), ''),
      split_part(u.email::text, '@', 1)
    ) as display_name,
    coalesce(u.raw_user_meta_data ->> 'nombre', '') as nombre,
    coalesce(u.raw_user_meta_data ->> 'apellidos', '') as apellidos,
    coalesce((u.raw_user_meta_data ->> 'is_admin')::boolean, false)
      or coalesce(u.raw_user_meta_data ->> 'role' = 'admin', false)
      or coalesce(u.raw_app_meta_data ->> 'role' = 'admin', false) as is_admin,
    coalesce((u.raw_user_meta_data ->> 'is_active')::boolean, true) as is_active,
    u.created_at
  from auth.users u
  order by 3 asc, 2 asc;
end;
$$;

grant execute on function public.get_employee_directory() to authenticated;

create or replace function public.get_attendance_report(
  filter_user_id uuid default null,
  filter_start_date date default null,
  filter_end_date date default null
)
returns table (
  id text,
  user_id uuid,
  employee_name text,
  employee_email text,
  attendance_date text,
  attendance_time text,
  tipo text,
  ubicacion text,
  descripcion text,
  latitud double precision,
  longitud double precision,
  ip text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  perform public.assert_hr_admin();

  return query
  select
    a.id::text,
    a.user_id,
    coalesce(
      nullif(u.raw_user_meta_data ->> 'display_name', ''),
      nullif(u.raw_user_meta_data ->> 'full_name', ''),
      nullif(trim(concat_ws(' ', u.raw_user_meta_data ->> 'nombre', u.raw_user_meta_data ->> 'apellidos')), ''),
      split_part(u.email::text, '@', 1)
    ) as employee_name,
    u.email::text as employee_email,
    to_char(timezone('America/Costa_Rica', a.created_at), 'YYYY-MM-DD') as attendance_date,
    to_char(timezone('America/Costa_Rica', a.created_at), 'HH24:MI:SS') as attendance_time,
    a.tipo::text,
    a.ubicacion::text,
    a.descripcion::text,
    a.latitud,
    a.longitud,
    a.ip::text,
    a.created_at
  from public.asistencias a
  join auth.users u on u.id = a.user_id
  where (filter_user_id is null or a.user_id = filter_user_id)
    and (
      filter_start_date is null
      or timezone('America/Costa_Rica', a.created_at)::date >= filter_start_date
    )
    and (
      filter_end_date is null
      or timezone('America/Costa_Rica', a.created_at)::date <= filter_end_date
    )
  order by employee_name asc, attendance_date asc, a.created_at asc;
end;
$$;

grant execute on function public.get_attendance_report(uuid, date, date) to authenticated;

create table if not exists public.attendance_locations (
  id bigint generated by default as identity primary key,
  name text not null unique,
  requires_description boolean not null default false,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists attendance_locations_set_updated_at on public.attendance_locations;
create trigger attendance_locations_set_updated_at
before update on public.attendance_locations
for each row
execute function public.touch_updated_at();

insert into public.attendance_locations (name, requires_description, sort_order, is_active)
values
  ('Oficina Central', false, 10, true),
  ('Cliente A', false, 20, true),
  ('Sucursal Sur', false, 30, true),
  ('Otro', true, 40, true)
on conflict (name) do nothing;

create or replace function public.get_attendance_locations()
returns table (
  id bigint,
  name text,
  requires_description boolean,
  sort_order integer
)
language sql
security definer
stable
set search_path = public
as $$
  select
    l.id,
    l.name,
    l.requires_description,
    l.sort_order
  from public.attendance_locations l
  where l.is_active = true
  order by l.sort_order asc, l.name asc;
$$;

grant execute on function public.get_attendance_locations() to authenticated;

create or replace function public.admin_list_attendance_locations()
returns table (
  id bigint,
  name text,
  requires_description boolean,
  sort_order integer,
  is_active boolean,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  perform public.assert_hr_admin();

  return query
  select
    l.id,
    l.name,
    l.requires_description,
    l.sort_order,
    l.is_active,
    l.created_at,
    l.updated_at
  from public.attendance_locations l
  order by l.sort_order asc, l.name asc;
end;
$$;

grant execute on function public.admin_list_attendance_locations() to authenticated;

create or replace function public.admin_upsert_attendance_location(
  location_id bigint default null,
  location_name text default null,
  location_requires_description boolean default false,
  location_sort_order integer default 0,
  location_is_active boolean default true
)
returns public.attendance_locations
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  saved_row public.attendance_locations;
begin
  perform public.assert_hr_admin();

  if location_name is null or btrim(location_name) = '' then
    raise exception 'El nombre del lugar es obligatorio.';
  end if;

  if location_id is null then
    insert into public.attendance_locations (
      name,
      requires_description,
      sort_order,
      is_active
    )
    values (
      btrim(location_name),
      location_requires_description,
      coalesce(location_sort_order, 0),
      location_is_active
    )
    returning * into saved_row;
  else
    update public.attendance_locations
    set
      name = btrim(location_name),
      requires_description = location_requires_description,
      sort_order = coalesce(location_sort_order, 0),
      is_active = location_is_active
    where id = location_id
    returning * into saved_row;

    if saved_row is null then
      raise exception 'No encontramos el lugar solicitado.';
    end if;
  end if;

  return saved_row;
end;
$$;

grant execute on function public.admin_upsert_attendance_location(bigint, text, boolean, integer, boolean) to authenticated;

create or replace function public.admin_delete_attendance_location(location_id bigint)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  perform public.assert_hr_admin();

  delete from public.attendance_locations
  where id = location_id;

  if not found then
    raise exception 'No encontramos el lugar solicitado.';
  end if;
end;
$$;

grant execute on function public.admin_delete_attendance_location(bigint) to authenticated;
